---
- name: "Setting up Environment"
  hosts:
    - IG
  become: yes
  tasks:
    - name: Deploy IG Server
      ansible.builtin.script:
        cmd: ../scripts/setting_up_env.sh
        register: results
    - name: debugmessage
      debug:
       msg: results.stdout
